### ISSUE TITLE
Error while parsing response: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by troidesss** [flozz/p0wny-shell#21]
Hi, i have error what can be wrong?

**Comment by flozz** [comment]
No idea what is going wrong, maybe PHP error are print in the middle of the JSON?

**Comment by void-m4110c** [comment]
You seem to have a problem in `function makeRequest(url, params, callback)`.

This happens if you have a `JSON.parse(xhr.responseText)` where `xhr.responseText` is not Json but an HTML page, that gets returned. Of course, this can not be parsed then as Json...

I had this error, when trying to run the shell on an application that was hosted on Windows. You don't have things like `/bin/bash` there. It seems the script is only useful on Linux hosts.

**Comment by flozz** [comment]
I know some people have it working with Windows but yes it is not the dev focus.

Also it is not normal you receive HTML content in response of the XHR.... Can you provide the content of the HTML page? is it a php error page?

**Comment by akr3ch** [comment]
> Hi, i have error what can be wrong?

it seems like, php is not installed on that target machine.

**Comment by cli-ish** [comment]
@flozz What is the state of this issue, is this still open?

**Comment by flozz** [comment]
I think we can close this issue :)
