### ISSUE TITLE
Error while parsing response: SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by Koykoy200078** [flozz/p0wny-shell#24]
I tried to input tasklist to view running process but it shows error

**Comment by flozz** [comment]
Hello,

The server probably returned an error instead of only a JSON. Can you check what is returned by the request? 

----

On the shell page,

* press `F12`,
* go to the `Network
* Find the last request and check what is in the `body` of the response

Example in Firefox:

![image](https://user-images.githubusercontent.com/971438/174586730-636e7f4d-3927-406f-b9b7-dde2970eaeb8.png)

Example in Chromium:

![image](https://user-images.githubusercontent.com/971438/174586800-50b25a86-d30b-4185-8abd-897ae6eeccde.png)

**Comment by Koykoy200078** [comment]
It show's no response 
![image](https://user-images.githubusercontent.com/31362410/174971329-e3d4a97e-db64-4590-9b2f-0102a60587e9.png)

**Comment by flozz** [comment]
Have you downloaded the script from this repository? The URLs do not match what is expected in the source (`commands` parameter instead of `feature`, `getPwd` instead of `pwd`, etc.) :thinking:

**Comment by Koykoy200078** [comment]
> Have you downloaded the script from this repository? The URLs do not match what is expected in the source (`commands` parameter instead of `feature`, `getPwd` instead of `pwd`, etc.) 🤔

sorry for the late reply, I forgot to subscribe the notification, I used the modified code from the code, but it's with the same problem
![1](https://user-images.githubusercontent.com/31362410/178390493-fb377fc0-bd4d-43a9-8bad-c503837b1f67.png)
![2](https://user-images.githubusercontent.com/31362410/178390522-f38d6b3d-999d-4ac8-97fc-d0215234d5d6.png)

**Comment by flozz** [comment]
Hum...

The response from the server is empty... Maybe there is some restricted functions on the server? Have you some errors in the php logs on the server?

**Comment by cli-ish** [comment]
If this is related to https://github.com/flozz/p0wny-shell/issues/32 it should be fixed.

I'm not sure if that's the case, since php would throw a 500 error code if something goes wrong. We can't debug it without knowing how the environment is set up.

@flozz I think this ticket can be closed.

**Comment by flozz** [comment]
Yeah you are right, we cannot do anything more on this issue, I close it :)
